#!/bin/bash

any_failed=0
num_tests=0
num_passed=0
for file in `find "tests/regression-tests/" -name "*.lst"`; do
 let num_tests=$num_tests+1

 part=(`echo ${file} | tr '/' ' '`)
 part[1]=''

 testfile=''
 for p in "${part[@]}"; do
  testfile="$testfile""$p"
  testfile="$testfile"'/'
 done

 ./pal "${testfile%.lst/}.pal" > /dev/null 2>&1
 rv=$?

 failed=0
 if [ $rv != 0 -a $rv != 1 ]
 then
   failed=1
   any_failed=1
 fi

 listing=''
 for p in "${part[@]}"; do
   listing="$p"
 done

 result=`diff "${file}" "${listing}"`
 if [ "$result" != "" ]
 then
   failed=1
   any_failed=1
 fi
 rm "${listing}"

 if [ $failed == 1 ]
 then
  echo "FAIL" "${file}"
 else
  echo "PASS" "${file}"
  let num_passed=$num_passed+1
 fi
done

echo ""
echo "$num_passed / $num_tests tests passed"

exit
